[package]
name = "clock-app"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
image = { version = "0.24", default-features = false, features = ["png"] }
chrono = "0.4"
pollster = "0.3"
rand = "0.8"
wgpu = "0.16"
wgpu_glyph = "0.20"
winit = "0.28"
