[package]
name = "clock-app"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
chrono = "0.4"
pollster = "0.3"
wgpu = "0.16"
wgpu_glyph = "0.20"
winit = "0.28"
